owner: keywordnew
repo: stockholm-watchtower
user-agent: keywordnew

sites:
  - name: Stockholm Vatten och Avfall
    url: https://www.stockholmvattenochavfall.se/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/water.png
  - name: E.ON SE
    url: https://www.eon.se/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/power-1.png
  - name: Telia Sverige AB
    url: https://www.telia.se/privat/mitt-telia
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/communication.png
  - name: Karolinska Institutet
    url: https://www.karolinska.se/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/hospital.png
  - name: Polismyndigheten
    url: https://polisen.se/utsatt-for-brott/polisanmalan/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/emergency.png
  - name: Storstockholms Lokaltrafik
    url: https://sl.se/privat/min-profil
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/transportation-1.png
  - name: Skandinaviska Enskilda Banken AB
    url: https://seb.se/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/payment.png


status-website:
  baseUrl: /stockholm-watchtower
  name: 'Neighbourhood Cyber'
  logoUrl: https://nilspace.xyz/content/images/2023/05/favicon.png
  favicon: https://nilspace.xyz/content/images/2023/05/favicon.png
  introTitle: 'Stockholm 🇸🇪 watchtower'
  introMessage: 'check if critical infrastructure may be down, or use GitHub ↗️ to "Watch" and get notified'
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Neighbourhoods
      href: https://github.com/$OWNER?tab=repositories&q=watchtower
      
i18n:
  footer: This Watchtower is part of [Project Watchtower](https://nilspace.xyz/project-watchtower/).
